/*
-- Query: SELECT * FROM tafp.stock_update
-- Date: 2021-12-30 14:21
*/
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (1,'Gadus chalcogrammus','ALK',3409,446,'2021-11-22 02:18:25','Alaska pollock(=Walleye poll.)','Alaska pollock(=Walleye poll.)','61','Theragra chalcogramma','ALK');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (2,'Euphausia superba','KRI',10515,446,'2021-11-22 02:18:25','Antarctic krill','Antarctic krill','58','NA','KRI');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (3,'Pleuragramma antarctica','ANS',5612,446,'2021-11-22 02:18:25','Antarctic silverfish','Antarctic silverfish','58','NA','ANS');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (4,'Gobionotothen gibberifrons','NOG',5585,446,'2021-11-22 02:18:25','Humped rockcod','Humped rockcod','48','Notothenia gibberifrons','NOG');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (5,'Penaeus indicus','PNI',10146,446,'2021-11-22 02:18:25','Indian white prawn','Indian white prawn','51','NA','PNI');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (6,'Haliporoides sibogae','JAQ',10450,446,'2021-11-22 02:18:25','Jack-knife shrimp','Jack-knife shrimp','51','NA','JAQ');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (7,'Scombridae','MAX',8518,446,'2021-11-22 02:18:25','Mackerels nei','Mackerels nei','51','NA','MAX');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (8,'Notothenia rossii','NOR',5578,446,'2021-11-22 02:18:25','Marbled rockcod','Marbled rockcod','58','NA','NOR');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (9,'Actinopterygii','MZZ',9482,446,'2021-11-28 20:20:49','Marine fishes nei','Marine fishes nei','71','Osteichthyes','MZZ');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (10,'Alosa immaculata','SHC',2918,446,'2021-11-22 02:18:25','Pontic shad','Pontic shad','37','Alosa pontica','SHC');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (11,'Sardinops sagax','CHP',7982,446,'2021-11-22 02:05:06','South American pilchard','California pilchard','77','Sardinops caeruleus','CPI');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (12,'Mizuhopecten yessoensis','JSC',11446,446,'2021-11-22 02:18:25','Yesso scallop','Yesso scallop','61','Patinopecten yessoensis','JSC');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (13,'Sardinops sagax','CHP',7982,446,'2021-11-22 01:44:17','South American pilchard','Japanese pilchard','61','Sardinops melanostictus','JAP');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (14,'Sardinops sagax','CHP',7982,446,'2021-11-22 01:44:17','South American pilchard','Southern African pilchard','47','Sardinops ocellatus','PIA');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (16,'Chlamys varia','VSC',11445,446,'2021-11-22 02:18:25','Variegated scallop','Variegated scallop','37','Chlamys varia','VSC');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (17,'Rostroraja alba','RJA',9208,446,'2021-11-22 02:18:25','White skate','White skate','37','Raja alba','RJA');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (18,'Leucoraja naevus','RJN',9211,446,'2021-11-22 02:18:25','Cuckoo ray','Cuckoo ray','37','Raja naevus','RJN');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (19,'Tritia mutabilis','NSQ',11142,446,'2021-11-22 02:18:25','Changeable nassa','Changeable nassa','37','Nassarius mutabilis','NSQ');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (20,'Magallana gigas','OYG',11303,446,'2021-11-22 02:18:25','Pacific cupped oyster','Pacific cupped oyster','37','Crassostrea gigas','OYG');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (21,'Microcosmus vulgaris','SSG',12566,446,'2021-11-22 02:18:25','Grooved sea squirt','Grooved sea squirt','37','Microcosmus sulcatus','SSG');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (22,'Dipturus batis','RJB',9187,446,'2021-11-28 20:10:19','Blue skate','Blue skate','37','Raja batis','RJB');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (23,'Dipturus oxyrinchus','RJO',9189,446,'2021-11-22 02:18:25','Longnosed skate','Longnosed skate','37','Raja oxyrinchus','RJO');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (24,'Kajikia albida','WHM',8156,446,'2021-11-22 02:18:25','Atlantic white marlin','Atlantic white marlin','37','Tetrapturus albidus','WHM');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (28,'Chelidonycthys cuculus','GUR',7779,446,'2021-11-22 02:18:25','Red gurnard','Red gurnard','37','Aspitrigla cuculus','GUR');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (29,'Balistes capriscus','TRG',6562,446,'2021-11-22 02:18:25','Grey triggerfish','Grey triggerfish','37','Balistes carolinensis','TRG');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (30,'Scophthalmus maximus','TUR',3279,446,'2021-11-29 03:07:21','Turbot','Turbot','37','Psetta maxima','TUR');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (31,NULL,'CTS',NULL,446,'2021-11-22 02:18:24',NULL,NULL,'37','Venerupis pullastra','CTS');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (32,'Lepidonotothen squamifrons','NOS',5587,446,'2021-11-22 01:46:59','Striped-eyed rockcod','Striped-eyed rockcod',NULL,'Notothenia kempi','NOK');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (33,'Sardinops sagax','CHP',7982,446,'2021-11-22 02:05:06','South American pilchard','Australian pilchard',NULL,'Sardinops neopilchardus','SRP');
INSERT INTO `` (`id`,`asfis_scientific_name`,`asfis_3a_code`,`stock_id`,`reference_id`,`date_update`,`asfis_common_name`,`fao_common_name`,`fao_area_code`,`fao_scientific_name`,`fao_3code`) VALUES (34,'Ostrea spp','OYX',11273,446,'2021-11-22 02:05:06','Flat oysters nei','New Zealand dredge oyster',NULL,'Ostrea lutaria','DRY');
